services:
  db:
    image: postgres:18.3-alpine
    restart: always
    environment:
      POSTGRES_DB: mitzieAuth
      POSTGRES_USER: mitzie
      POSTGRES_PASSWORD: TEST123!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: